language: ruby
cache: bundler
rvm:
  - "2.3"

env:
  - DB=postgresql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec
before_script:
  - bundle exec rake db:create
bundler_args: --binstubs=./bundler_stubs

# 5. OPTIONAL Add a Build Status Badge to your README, follow instructions here:
#    http://docs.travis-ci.com/user/status-images/

# Suggested docs
# --------------
# Getting Started: http://docs.travis-ci.com/user/getting-started/
# Ruby & Travis CI docs: http://docs.travis-ci.com/user/languages/ruby/
# Supported Ruby Versions: http://rubies.travis-ci.org/
# Custom build task: http://docs.travis-ci.com/user/customizing-the-build/
# GUI, Browsers, xvfb: http://docs.travis-ci.com/user/gui-and-headless-browsers/
# Build Status Badge for README: http://docs.travis-ci.com/user/status-images/

