ISSUES = [
  "Health",
  "Health Insurance",
  "Mental Health",
  "Public Health",
  "Womens Health",
  "Defense Policy",
  "Defense Spending",
  "Defense",
  "Armed Forces And National Security",
  "Homeland Security",
  "Energy Security",
  "Economic Security",
  "Armed Forces And National Security",
  "Social Security",
  "Security",
  "Taxation",
  "Corporation Taxes",
  "Employment Taxes",
  "Capital Gains Tax",
  "Carbon Taxes",
  "Estate Tax",
  "Excise Tax",
  "Income Tax",
  "Personal Income Tax",
  "Property Tax",
  "Sales Tax",
  "Tax Cuts",
  "Tax Policy",
  "Tax Reform",
  "International Affairs",
  "International Finance",
  "International Law",
  "International Relations",
  "Landscape Protection",
  "Open Space Lands",
  "Public Lands And Natural Resources",
  "Public Lands",
  "Alternative And Renewable Resources",
  "Conservation Of Natural Resources",
  "Freshwater Resources Conservation",
  "Marine Resources",
  "Marine Resources Conservation",
  "Natural Resources",
  "Mines And Mineral Resources",
  "Renewable Natural Resources",
  "Water Resources",
  "Computer Crimes",
  "Crime And Law Enforcement",
  "Crime Prevention",
  "Crime Victims",
  "Crimes Against Children",
  "Crimes Against Humanity",
  "Crimes Against Women",
  "Drugs And Crime",
  "Juvenile Crime And Gang Violence",
  "Hate Crimes",
  "Fraud Offenses And Financial Crimes",
  "Political Crimes",
  "Sex Crimes",
  "Violent Crime",
  "White Collar Crime",
  "Discrimination In Law Enforcement",
  "Drug Law Enforcement",
  "Law Enforcement",
  "Adult Education",
  "Bilingual Education",
  "Computers In Education",
  "Continuing Education",
  "Education",
  "Education Funding",
  "Educational Policy",
  "Educational Reform",
  "Educational Vouchers",
  "Science And Engineering Education",
  "Secondary Education",
  "Special Education",
  "Vocational Education",
  "Congress",
  "Congressional Budget",
  "Congressional Districts",
  "Congressional Elections",
  "Congressional Ethics",
  "Congressional Investigations",
  "Campaign Finance Reform",
  "Corporate Finance",
  "Economics And Public Finance",
  "Finance",
  "Foreign Trade And International Finance",
  "Housing Finance",
  "Transportation",
  "Transportation And Public Works",
  "Transportation Policy",
  "Transportation Safety",
  "Urban Transportation",
  "Immigration",
  "Border Security And Unlawful Immigration",
  "Immigration Law",
  "Immigration Policy",
  "Labor",
  "Labor And Employment",
  "Labor Disputes",
  "Labor Policy",
  "Labor Unions",
  "Skilled Labor",
  "Unskilled Labor",
  "Discrimination In Employment",
  "Employment",
  "Employment At Will",
  "Womens Employment",
  "Veterans Employment",
  "Unemployment",
  "Alternative Energy Sources",
  "Biomass Energy",
  "Energy",
  "Energy Conservation",
  "Energy Policy",
  "Energy Research",
  "Nuclear Energy",
  "Solar Energy",
  "Environmental Justice",
  "Environmental Protection",
  "Science",
  "Science Policy",
  "Biotechnology",
  "Computers And Information Technology",
  "Medical Technology",
  "Technology",
  "Technology Policy",
  "Commerce",
  "Agriculture",
  "Agriculture And Food",
  "Sustainable Agriculture",
  "Food",
  "Food Prices",
  "Food Stamps",
  "Natural Foods",
  "Civil Liberties",
  "Civil Rights",
  "Animal Rights",
  "Employee Rights",
  "First Amendment Rights",
  "Gay Rights",
  "Human Rights",
  "Property Rights",
  "Voting Rights",
  "Water Rights",
  "Womens Rights",
  "Native Americans",
  "Public Welfare",
  "Social Welfare",
  "Welfare",
  "Welfare Reform",
  "Affordable Housing",
  "Fair Housing",
  "Housing",
  "Housing Finance",
  "Housing Policy",
  "Administrative Law",
  "Antitrust Law",
  "Banking Law",
  "Constitutional Law",
  "Criminal Law",
  "Drug Law And Legislation",
  "Election Law",
  "Law",
  "Law Reform",
  "Arts Culture Religion",
  "Religion",
  "Abortion",
  "Art"
]

# STATES = {
#     AK: "Alaska",
#     AL: "Alabama",
#     AR: "Arkansas",
#     AS: "American Samoa",
#     AZ: "Arizona",
#     CA: "California",
#     CO: "Colorado",
#     CT: "Connecticut",
#     DC: "District of Columbia",
#     DE: "Delaware",
#     FL: "Florida",
#     GA: "Georgia",
#     GU: "Guam",
#     HI: "Hawaii",
#     IA: "Iowa",
#     ID: "Idaho",
#     IL: "Illinois",
#     IN: "Indiana",
#     KS: "Kansas",
#     KY: "Kentucky",
#     LA: "Louisiana",
#     MA: "Massachusetts",
#     MD: "Maryland",
#     ME: "Maine",
#     MI: "Michigan",
#     MN: "Minnesota",
#     MO: "Missouri",
#     MS: "Mississippi",
#     MT: "Montana",
#     NC: "North Carolina",
#     ND: "North Dakota",
#     NE: "Nebraska",
#     NH: "New Hampshire",
#     NJ: "New Jersey",
#     NM: "New Mexico",
#     NV: "Nevada",
#     NY: "New York",
#     OH: "Ohio",
#     OK: "Oklahoma",
#     OR: "Oregon",
#     PA: "Pennsylvania",
#     PR: "Puerto Rico",
#     RI: "Rhode Island",
#     SC: "South Carolina",
#     SD: "South Dakota",
#     TN: "Tennessee",
#     TX: "Texas",
#     UT: "Utah",
#     VA: "Virginia",
#     VI: "Virgin Islands",
#     VT: "Vermont",
#     WA: "Washington",
#     WI: "Wisconsin",
#     WV: "West Virginia",
#     WY: "Wyoming"
# }

ISSUES.each do |issue|
  Issue.create(name: issue, slug: issue.parameterize)
end

# STATE.each do |abbrev, name|
#   State.create(name: name, abbreviation: abbrev)
# end